name: Continuous Deployment

on:
  push:
    branches: [main]

env:
  TESTING: ${{ secrets.TESTING }}
  BASE_METEX_API_URL: ${{ secrets.BASE_METEX_API_URL }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  DB_SRV: ${{ secrets.DB_SRV }}
  EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/golab-backend
            git pull origin main
            pip install --no-cache-dir -r requirements.txt
            pm2 restart golab-backend
    continue-on-error: true

  rollback:
    needs: deploy
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Rollback EC2 Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/golab-backend
            git reset --hard HEAD~1
            pm2 restart golab-backend